baseURL = "//localhost/how-to-build-single-page-application-with-react"
publishDir = "docs"


languageCode = "en-us"
title = "How to build Single Page Application with React and Redux"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
title_suffix = "Best practices with React and Redux"
description = "How to build Single Page Application with React and Redux"
disableLogo = true

[[menu.shortcuts]]
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/SanderV1992"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20
